### ISSUE TITLE
I found that there is no clock_type file in the rclpy directory under my ros2 directory.

### ISSUE THREAD

**Issue by lijianfromearth** [ros2/rclpy#1327]
I meet no moudle  ClockType,then i found there is no clock_type.py file in the rclpy directory.
I download this file from GitHub，then I encountered this error:

from rclpy.clock_type import ClockType
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/clock_type.py", line 20, in <module>
    class ClockType(IntEnum):
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/clock_type.py", line 27, in ClockType
    UNINITIALIZED = _rclpy.ClockType.UNINITIALIZED
AttributeError: module 'rclpy._rclpy' has no attribute 'ClockType'

I have tried to recompile it using your method
this:
mkdir -p rclpy_ws/src
cd rclpy_ws/src
git clone https://github.com/ros2/rclpy.git
cd ..
colcon build --symlink-install

but this clone also does not hava clock_type.py.

The functionality of my code has already been implemented using other methods, I'm just reporting this error here.

**Comment by fujitatomoya** [comment]
> UNINITIALIZED = _rclpy.ClockType.UNINITIALIZED

is introduced by https://github.com/ros2/rclpy/pull/1235

and rolling has this file, https://github.com/ros2/rclpy/blob/rolling/rclpy/rclpy/clock_type.py

> git clone https://github.com/ros2/rclpy.git

i believe you are using foxy, which is already end of life. but something you need to do is to build with `foxy`?

```bash
git clone -b foxy https://github.com/ros2/rclpy.git
```

**Comment by lijianfromearth** [comment]
thank you
